#生产环境
spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://rm-bp1fa2vc92hmmo652co.mysql.rds.aliyuncs.com:3306/user-center?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSH=false
    username: chenlong
    password: CL2020love
    driver-class-name: com.mysql.jdbc.Driver
    #session失效时间
  session:
    timeout: 86400