#生产环境
spring:
  datasource:
    url: jdbc:mysql://Your_Prod_Envir_Addr:3306/user-center?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: chenlong
    password: CL2020love
    driver-class-name: com.mysql.jdbc.Driver
    #session失效时间
  session:
    timeout: 86400
